export const __code__prefix__: string = "code:";

export const __code__exp__: number = 60 * 10; // 10m

export enum Events {
  ON_USER_JOIN_SPACE = "ON_USER_JOIN_SPACE",
  ON_UPDATE_USER_SETTINGS = "ON_UPDATE_USER_SETTINGS",
  ON_USER_LEAVE_SPACE = "ON_USER_LEAVE_SPACE",
  ON_AUTH_STATE_CHANGE = "ON_AUTH_STATE_CHANGE",
  ON_NEW_MESSAGE = "ON_NEW_MESSAGE",
  ON_NEW_CHAT_MESSAGE = "ON_NEW_CHAT_MESSAGE",
  USER_ONLINE = "USER_ONLINE",
  ON_READ_MESSAGES = "ON_READ_MESSAGES",
  ON_NEW_USER_JOINED = "ON_NEW_USER_JOINED",
  ON_PROFILE_DETAILS_UPDATE = "ON_PROFILE_DETAILS_UPDATE",
  ON_NEW_DEVICE_AUTHENTICATION = "ON_NEW_DEVICE_AUTHENTICATION",
  ON_USER_TYPING = "ON_USER_TYPING",
  ON_MESSAGE_REACTION = "ON_MESSAGE_REACTION",
  ON_DELETE_MESSAGE = "ON_DELETE_MESSAGE",
  ON_UN_SEND_MESSAGE = "ON_UN_SEND_MESSAGE",
  ON_MESSAGE_REACTION_NOTIFICATION = "ON_MESSAGE_REACTION_NOTIFICATION",
}
