export const __code__prefix__: string = "code:";

export const __code__exp__: number = 60 * 10; // 10m

export enum Events {
  NOTIFY_EVENT = "NOTIFY_EVENT",
  ON_AUTH_STATE_CHANGE = "ON_AUTH_STATE_CHANGE",
  ON_NEW_MESSAGE = "ON_NEW_MESSAGE",
  ON_NEW_CHAT_MESSAGE = "ON_NEW_CHAT_MESSAGE",
  USER_ONLINE = "USER_ONLINE",
  ON_READ_MESSAGES = "ON_READ_MESSAGES",
  ON_NEW_USER_JOINED = "ON_NEW_USER_JOINED",
  ON_PROFILE_DETAILS_UPDATE = "ON_PROFILE_DETAILS_UPDATE",
  ON_NEW_DEVICE_AUTHENTICATION = "ON_NEW_DEVICE_AUTHENTICATION",
}
