version: "3.9"
services:
  redisdb:
    image: redis:7.0.8-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redisdb:/data
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - /database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 54321
    environment:
      POSTGRES_DB: askme
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      SERVICE_TAGS: dev

networks:
  bridge:
    external: true
    name: bridge
volumes:
  postgresdb:
    driver: local
  redisdb:
    driver: local
